spring:
  application:
    name: config-client
  cloud:
    bus:
      enabled: true
     trace:
       enabled: true
    config:
      label: master
      profile: dev
    discovery:
      enabled: true
      serviceId: config-server
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
server:
  port: 8881

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/

