spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 0.0.0.0
    port: 5762
    username: guest
    password: guest
#      uri: http://localhost:8888/

server:
  port: 8881
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

